# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCouncilsearch():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_councilsearch(self):
    self.driver.get("https://www.linkedin.com/")
    self.driver.set_window_size(550, 691)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("borzhemsky@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("5YXoEfx2sOiGD6xdQlHz")
    self.driver.find_element(By.CSS_SELECTOR, ".btn__primary--large").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn__secondary--large-muted").click()
    self.driver.find_element(By.CSS_SELECTOR, ".search-global-typeahead__input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".search-global-typeahead__input").send_keys("web developer city council")
    self.driver.find_element(By.CSS_SELECTOR, ".search-global-typeahead__input").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "See all people results").click()
    self.vars["result1"] = self.driver.find_element(By.CSS_SELECTOR, ".reusable-search__result-container:nth-child(1) .entity-result__primary-subtitle").text
    self.driver.execute_script("window.scrollTo(0,366)")
    self.driver.find_element(By.CSS_SELECTOR, "#ember484 .mercado-match").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.vars["result2_sub"] = self.driver.find_element(By.CSS_SELECTOR, ".reusable-search__result-container:nth-child(3) strong:nth-child(2)").text
    self.vars["result3_sub"] = self.driver.find_element(By.CSS_SELECTOR, ".reusable-search__result-container:nth-child(2) .white-space-pre:nth-child(8)").text
    self.vars["result4_sub_long"] = self.driver.find_element(By.CSS_SELECTOR, ".reusable-search__result-container:nth-child(6) .entity-result__summary").text
    self.driver.find_element(By.CSS_SELECTOR, "#ember627 > .artdeco-button__text").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, "#ember707 > .artdeco-button__text").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.vars["result5"] = self.driver.find_element(By.CSS_SELECTOR, ".reusable-search__result-container:nth-child(9) .entity-result__primary-subtitle").text
    self.vars["result5_sub"] = self.driver.find_element(By.CSS_SELECTOR, ".reusable-search__result-container:nth-child(9) .entity-result__summary").text
    self.vars["result6"] = self.driver.find_element(By.CSS_SELECTOR, ".reusable-search__result-container:nth-child(8) .entity-result__primary-subtitle").text
  
